baseurl = "https://cv.mansheim.com/"

disable404 = true

disableRSS = true

disableSitemap = true

googleAnalytics = "UA-XXXXXXX-Y"

languageCode = "en-us"

theme = "hugo-orbit-theme"

title = "Ben Mansheim - Senior Documentation Specialist"

[params]

author = "Pavel Kanyshev"

description = "Ben - Doc'er for software"

styles = "styles.css"

[params.contact]

enable = true

[[params.contact.list]]

class = "email"

icon = "fa-envelope"

title = "cv@mansheim.com"

url = "mailto:cv@mansheim.com"

[[params.contact.list]]

class = "phone"

icon = "fa-phone"

title = "+972 (0)52 6916188"

[[params.contact.list]]

class = "website"

icon = "fa-globe"

title = "cv.mansheim.com"

url = "//cv.mansheim.com"

[[params.contact.list]]

class = "linkedin"

icon = "fa-linkedin"

title = "bmansheim"

url = "//linkedin.com/in/bmansheim"

[[params.contact.list]]

class = "github"

icon = "fa-github"

title = "bmansheim"

url = "//github.com/bmansheim"

[params.education]

enable = true

title = "Education"

[[params.education.list]]

college = "University of Wisconsin-Madison"

dates = "1992-1995"

degree = "BA with focus on Applied Math, Engineering and Physics"

[params.experiences]

enable = true

icon = "fa-briefcase"

title = "Experiences"

[params.footer]

copyright = ""

[params.interests]

enable = true

title = "Interests"

[[params.interests.list]]

interest = "Guitar"

[[params.interests.list]]

interest = "Boxing"

[[params.interests.list]]

interest = "Classic texts"

[[params.jobs.list]]

company = "Redis Labs - Tel Aviv, Israel"

dates = "2018 - Present"

details = "I am responsible for all aspects of the documentation. My main goal is to integrate documentation into the release process. I was hired to migrate the documentation set from WordPress to Docs-as-Code and revamp the documentation site. Tools: GitHub, Markdown, Hugo, CSS, AWS S3"

position = "Sr Technical Writer and Documentation Manager"

[[params.jobs.list]]

company = "Cloudify Platform Ltd - Herzliya, Israel"

dates = "2017 - 2018"

details = "As the first full-time writer at a cloud computing startup with a Linux environment, I evaluated current state of documentation and planned new strategy. As a result I relaunched the Docs-as-Code documentation process and revamped documentation site. Tools: GitHub, Markdown, Hugo, CSS, AWS S3, Rackspace"

position = "Sr Technical Writer and Documentation Manager"

[[params.jobs.list]]

company = "JBS Technical Writing - Netanya, Israel"

dates = "2017 – 2017"

details = "As a JBS consultant, I was the first writer at a data science startup. I evaluated the current state of documentation and planned new strategy. In addition, I interviewed engineers to rewrite significant sections of the KnowledgeBase. Tools: Google Docs, FreshDesk"

position = "Sr Technical Writer and Documentation Manager"

[[params.jobs.list]]

company = "Tufin Technologies Ltd. - Ramat Gan, Israel"

dates = "2011 - 2017"

details = "During my tenure at Tufin, I was the primary writer in the 150 member R&D organization working in Agile methodology. My tasks included terminology, user-interface texts, and user documentation for 3 products. I publish documentation to PDF, in-product help and online knowledgebase. During that time, I improve documentation processes, including implementing KnowledgeBase enhancements, managing contract writers, and starting new initiatives to deliver more value to customers.Tools: Author-it, Google Docs, Microsoft Word, CSS"

position = "Sr Technical Writer and Documentation Manager"

[params.language]

enable = true

title = "Languages"

[[params.language.list]]

language = "English"

level = "Native"

[[params.language.list]]

language = "Hebrew"

level = "Professional"

[[params.language.list]]

language = "German"

level = "Introductory"

[params.profile]

avatar = "face_shot.png"

name = "Ben Mansheim"

tagline = "Documentation Manager and Senior Technical Writer"

[params.projects]

enable = false

icon = "fa-archive"

intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

title = "Projects"

[[params.projects.list]]

tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

title = "Hugrid"

url = "https://github.com/aerohub/hugrid"

[[params.projects.list]]

tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

title = "Simple FAQ Theme for Hugo"

url = "https://github.com/aerohub/hugo-faq-theme"

[[params.projects.list]]

tagline = "Little profile/card-style template for Hugo."

title = "Hugo Identity"

url = "https://github.com/aerohub/hugo-identity-theme"

[[params.projects.list]]

tagline = "Hugo Resume/CV Theme for Developers."

title = "Orbit"

url = "https://github.com/aerohub/hugo-orbit-theme"

[[params.projects.list]]

tagline = "A simple responsive Hugo theme for personal site."

title = "Me"

url = "https://github.com/aerohub/hugo-me-theme"

[params.skills]

enable = true

icon = "fa-rocket"

title = "Areas of expertise over 18 years of leadership"

[[params.skills.list]]

level = "100%"

skill = "Computer Networking"

[[params.skills.list]]

level = "83%"

skill = "Project Management"

[[params.skills.list]]

level = "66%"

skill = "Software Documentation"

[[params.skills.list]]

level = "61%"

skill = "Simplified Technical English"

[[params.skills.list]]

level = "45%"

skill = "Documentation Management"

[[params.skills.list]]

level = "50%"

skill = "Docs-like-Code"

[params.summary]

enable = true

icon = "fa-user"

summary = "My experience in documentation grows out of a successful start in network administration and project management. The skills from these areas led me to manage all aspects of documentation for fast-growing hi-tech companies, including moving from waterfall to agile development management. As a writer and then a team lead I implemented documentation project lifecycle and the Simplified English standard to reduce the documentation project cycle by 50% and increase writer efficiency by 30%. After following the standard trends of documentation up the levels of responsibility, I now jumped into a startup that depends on Git and a static site generator to build their documentation, where I learned the process quickly and made immediate improvements for higher customer satisfaction."

title = "Career Profile"
