version: 2
jobs:
  # The build job
  build:
      working_directory: ~/project
      docker:
          - image: markgrimes/git-hugo-aws
      steps:
          # Checkout the code from the branch into the working_directory
          - checkout
          # Log the current branch
          - run:
              name: Show current branch
              command: echo ${CIRCLE_BRANCH}
          - run:
              name: Building
              command: hugo -v
          # Set the signature version for the S3 auth
          - run:
              name: Setting Signature Version 4 for S3 Request Authentication
              command: aws configure set default.s3.signature_version s3v4
          # Deploy to the S3 bucket corresponding to the current branch
          - run:
              name: Deploy to S3
              command: aws s3 sync public s3://hugo-test-1/cv

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
      jobs:
          - build
